### ISSUE TITLE
Feedback on detect flag

### ISSUE THREAD

**Issue by ajeema** [victorca25/iNNfer#1]
Hey guys, here is a quick and dirty for using scene detect for better scene detection instead of static GOP. The first part is working (Detecting scenes and populating the scenes.ini) but it's a hack and I commented out some things for testing. Definitely
 needs a lot more work but a rough starting point for discussion. 

[run.py.zip](https://github.com/victorca25/iNNfer/files/7079331/run.py.zip)

**Comment by efonte** [comment]
In my other fork (https://github.com/efonte/ESRGAN) I had the detection of the scenes with pyscenedetect and as it was a bit slow I had not added it in this script.

I just made a commit adding the optional parameter `--detect-scenes`.

You can see until the changes are merged the updated script here: https://github.com/efonte/iNNfer

**Comment by ajeema** [comment]
ok interesting, I made some similar additions to my fork. I found setting the downscale factor to 12 doubled the speed. I also added audio extraction as I could see it being done

**Comment by ajeema** [comment]
this can also be done with ffprobe but it's less straightforward and not significantly faster than scenedetect

**Comment by victorca25** [comment]
The dev branch has now been updated with the latest changes, including the automatic image splitter, when upscaling images that don't fit in VRAM. @ajeema we did some tests yesterday and it seems to work fine, but let us know if you test and something doesn't look right. 
Regarding the detection, I see there are many options, it would be a matter of comparing them, specially on speed and accuracy, but we can do that over time :D

**Comment by ajeema** [comment]
Thank you @victorca25 I'll take a look.

**Comment by ajeema** [comment]
--detect-scenes seems to be ignored when I try it and defaults to the 250 GOP. What am I doing wrong?
